Enrich expense to gender details to Payee
egovernments/DIGIT-Works pull request #1210
Opened 2023-07-06 11:03 UTC by ajay-egov

@shailesh-egov @jagankumar-egov

2023-07-12 04:12 UTC, shailesh-egov requested changes

2023-07-12 04:12 UTC, shailesh-egov commented on backend/expense/src/main/java/org/egov/digit/expense/web/models/IndividualSearch.java
> +package org.egov.digit.expense.web.models;
@ajay-egov we can not copy IndividualSearch model here. use Map to create these.

2023-07-12 04:12 UTC, shailesh-egov commented on backend/expense/src/main/java/org/egov/digit/expense/web/models/IndividualSearchRequest.java
> +package org.egov.digit.expense.web.models;
@ajay-egov we can not copy IndividualSearchRequest model here. use Map to create these.

2023-07-12 04:12 UTC, shailesh-egov commented on backend/muster-roll/src/main/java/org/egov/util/MusterRollServiceUtil.java
> +		additionalDetails.put("gender",matchedIndividual.getGender());
@ajay-egov this is muster roll service move this into another PR.

2023-07-12 04:12 UTC, shailesh-egov commented on backend/expense/src/main/java/org/egov/digit/expense/util/EnrichmentUtil.java
> +            billDetail.getPayee().setAdditionalDetails(additionalDetails);
@ajay-egov you are replacing the data of additional details without maintaining the existing available data.

2023-07-14 04:46 UTC, shailesh-egov approved these changes

2023-07-14 09:30 UTC, subhashini-egov approved these changes
Commenting basis approval from Shailesh.

2023-07-14 09:30 UTC, merged