PFM-4664-Tech-Debt-Code-lint-recommendations-across-all-modules-expense-calculator
egovernments/DIGIT-Works pull request #1571
Opened 2023-12-07 08:11 UTC by ansh-egov

2023-12-14 10:15 UTC, shubhang-eGov requested changes

2023-12-14 10:15 UTC, shubhang-eGov commented on backend/expense-calculator/src/main/java/org/egov/digit/expense/calculator/util/WorkflowUtil.java
> -import java.util.Collections;
Remove this empty class

2023-12-18 04:29 UTC, shailesh-egov approved these changes

2023-12-18 05:40 UTC, shailesh-egov approved these changes

2023-12-18 05:41 UTC, shailesh-egov commented on backend/expense-calculator/src/main/java/org/egov/digit/expense/calculator/util/WorkflowUtil.java
> -import java.util.Collections;
resolved

2023-12-18 05:43 UTC, shubhang-eGov approved these changes

2023-12-18 05:43 UTC, merged