Hcmpre 1645: Modification of Attendance Service for Payments use case
egovernments/DIGIT-Works pull request #1853
Opened 2024-12-17 05:59 UTC by yashita-egov

2024-12-30 08:52 UTC, shubhang-eGov commented on backend/attendance/src/main/resources/db/migration/main/V20241217103530__alter_attendance_table.sql
> +ALTER TABLE eg_wms_attendance_register ADD COLUMN IF NOT EXISTS paymentStatus character varying(64);
this is not paymentStatus, it should be wfStatus

2024-12-30 08:52 UTC, shubhang-eGov commented on backend/attendance/src/main/java/org/egov/web/models/PaymentStatus.java
> +			if (String.valueOf(b.value).equals(text)) {
equalsIgnoreCase instead of equals. And WfStatus instead of PaymentStatus

2024-12-30 08:52 UTC, shubhang-eGov commented on backend/attendance/src/main/java/org/egov/validator/AttendanceServiceValidator.java
> +//    }
Why are validators commented, make it configurable according to use cases

2024-12-30 08:52 UTC, shubhang-eGov commented on backend/attendance/src/main/java/org/egov/web/models/AttendanceRegisterSearchCriteria.java
> +    private List<String> referenceId;
This will break the existing UI, add another field, which will be internal just for using the IN query.

2025-01-02 06:56 UTC, holashchand requested changes

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/web/models/AttendanceRegisterSearchCriteria.java
> +    private List<String> referenceId;
Yashita, don't change this directly, our changes should be backward compatible and shouldn't break existing implementation. We can add another field `private List<String> referenceIds;`

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/web/models/AttendanceRegisterSearchCriteria.java
> +    private List<String> localityCode;
Attendance registers are being searched by a single locality code always, so change it to a string field

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/web/models/AttendanceRegisterSearchCriteria.java
> +    private PaymentStatus paymentStatus;
let it be a String field, allowing extension of the field usage

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/web/controllers/AttendanceApiController.java
> +        AttendanceRegisterResponse attendanceRegisterList = attendanceRegisterService.searchAttendanceRegister(requestInfoWrapper, searchCriteria);
rename variable attendanceRegisterList properly

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/web/controllers/AttendanceApiController.java
> +        this.registerRepository = registerRepository;
where and why are we using repository directly in the controller?

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/validator/AttendanceServiceValidator.java
> +//    private void validateStatus(List<AttendanceRegister> attendanceRegisters, Map<String, String> errorMap) {
we shouldn't be committing a commented code, remove it if not used.

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/validator/AttendanceServiceValidator.java
> +        boundaryServiceUtil.validateLocalityCode(request.getRequestInfo(), request.getAttendanceRegister(), AttendanceRegister::getTenantId, AttendanceRegister::getLocalityCode, errorMap);
make it configurable

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/validator/AttendanceServiceValidator.java
> +                    .referenceId(Collections.singletonList(referenceId))
leave it as it was, make changes in the query builder instead

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/validator/AttendanceServiceValidator.java
> +        boundaryServiceUtil.validateLocalityCode(request.getRequestInfo(), request.getAttendanceRegister(), AttendanceRegister::getTenantId, AttendanceRegister::getLocalityCode, errorMap);
make it configurable

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/util/ProjectServiceUtil.java
> +			builder.append("&ancestorIds=").append(referenceId);
child required is not related to ancestorIds here, so make separate if condition

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/util/AttendanceServiceConstants.java
> +    );
don't hardcode it, but make this configurable from the application.properties

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/service/AttendanceRegisterService.java
> +            counts = updateSearchCriteriaAndFetchAndFilterRegisters(requestInfoWrapper, registers, searchCriteria, resultAttendanceRegisters);
here param resultAttendanceRegisters can be changed to AttendanceRegisterResponse instead of returning count and adding registers separately

2025-01-02 06:56 UTC, holashchand commented on backend/attendance/src/main/java/org/egov/repository/RegisterRepository.java
> +        for (Map.Entry<String, String> entry : STATUS_MAP.entrySet()) {
make it configurable using param or env

2025-01-03 05:41 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/web/controllers/AttendanceApiController.java
> +        this.registerRepository = registerRepository;
removed

2025-01-03 10:45 UTC, yashita-egov commented on backend/attendance/src/main/resources/db/migration/main/V20241217103530__alter_attendance_table.sql
> +ALTER TABLE eg_wms_attendance_register ADD COLUMN IF NOT EXISTS paymentStatus character varying(64);
renamed it to reviewStatus

2025-01-03 10:45 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/validator/AttendanceServiceValidator.java
> +//    }
added

2025-01-03 10:45 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/web/models/AttendanceRegisterSearchCriteria.java
> +    private List<String> referenceId;
added

2025-01-03 10:45 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/web/models/AttendanceRegisterSearchCriteria.java
> +    private List<String> referenceId;
added

2025-01-03 10:46 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/web/models/AttendanceRegisterSearchCriteria.java
> +    private List<String> localityCode;
changed it to String and removed isChildrenRequired

2025-01-03 10:46 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/web/models/AttendanceRegisterSearchCriteria.java
> +    private PaymentStatus paymentStatus;
changed it to String reviewStatus

2025-01-03 10:46 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/web/controllers/AttendanceApiController.java
> +        AttendanceRegisterResponse attendanceRegisterList = attendanceRegisterService.searchAttendanceRegister(requestInfoWrapper, searchCriteria);
renamed

2025-01-03 10:47 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/validator/AttendanceServiceValidator.java
> +//    private void validateStatus(List<AttendanceRegister> attendanceRegisters, Map<String, String> errorMap) {
added configurable validators

2025-01-03 10:47 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/validator/AttendanceServiceValidator.java
> +        boundaryServiceUtil.validateLocalityCode(request.getRequestInfo(), request.getAttendanceRegister(), AttendanceRegister::getTenantId, AttendanceRegister::getLocalityCode, errorMap);
done..

2025-01-03 10:47 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/validator/AttendanceServiceValidator.java
> +                    .referenceId(Collections.singletonList(referenceId))
done

2025-01-03 10:47 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/validator/AttendanceServiceValidator.java
> +        boundaryServiceUtil.validateLocalityCode(request.getRequestInfo(), request.getAttendanceRegister(), AttendanceRegister::getTenantId, AttendanceRegister::getLocalityCode, errorMap);
made it configurable

2025-01-03 10:47 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/util/ProjectServiceUtil.java
> +			builder.append("&ancestorIds=").append(referenceId);
done

2025-01-03 10:48 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/util/AttendanceServiceConstants.java
> +    );
make it configurable

2025-01-03 10:48 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/service/AttendanceRegisterService.java
> +            counts = updateSearchCriteriaAndFetchAndFilterRegisters(requestInfoWrapper, registers, searchCriteria, resultAttendanceRegisters);
added param AttendanceRegisterResponse

2025-01-03 10:48 UTC, yashita-egov commented on backend/attendance/src/main/java/org/egov/repository/RegisterRepository.java
> +        for (Map.Entry<String, String> entry : STATUS_MAP.entrySet()) {
done

2025-01-13 07:10 UTC, Shashwat12-egov commented on backend/attendance/src/main/java/org/egov/enrichment/RegisterEnrichment.java
In staff enrichment during attendance register search, staffName is also being enriched in additional details object.

2025-01-13 07:14 UTC, Shashwat12-egov commented on backend/attendance/src/main/java/org/egov/enrichment/StaffEnrichmentService.java
While creating the attendance staff, staffName is fetched through staff userId sent through request body and is enriched in additional details object.

2025-01-13 08:59 UTC, Shashwat12-egov commented on backend/attendance/src/main/java/org/egov/repository/RegisterRepository.java
Created the getRegisterCounts function to get the total counts and status counts (APPROVED and PENDINGFORAPPROVAL). Sum Query is created inside that function to calculate the counts and totalCount is the total number of data based on search criteria including reviewStatus whereas status count is the number of data having approved review status count and pending for approval status count based on search criteria without reviewStatus.

2025-01-13 09:01 UTC, Shashwat12-egov commented on backend/attendance/src/main/java/org/egov/repository/querybuilder/RegisterQueryBuilder.java
Addition of servicecode, localitycode and reviewstatus in the model and coressponding changes in query building functons.

2025-01-13 09:05 UTC, Shashwat12-egov commented on backend/attendance/src/main/java/org/egov/repository/querybuilder/StaffQueryBuilder.java
Adding staffType variable in staffPermission model and making coressponding changes in the querybuilding function.

2025-01-13 09:06 UTC, Shashwat12-egov commented on backend/attendance/src/main/java/org/egov/repository/rowmapper/RegisterRowMapper.java
Changes in the row mapper for the new variables added (localitycode and reviewStatus).

2025-01-13 09:06 UTC, Shashwat12-egov commented on backend/attendance/src/main/java/org/egov/repository/rowmapper/StaffRowMapper.java
Changes in the row mapper for the new variables added (staffType).

2025-01-13 09:09 UTC, Shashwat12-egov commented on backend/attendance/src/main/java/org/egov/service/StaffService.java
Function to fetch the first owner staff instead of first staff search.

2025-01-13 09:22 UTC, Shashwat12-egov commented on backend/attendance/src/main/java/org/egov/web/models/StaffType.java
StaffType is a enum class.

2025-01-13 09:23 UTC, Shashwat12-egov commented on backend/attendance/src/main/resources/db/migration/main/V20241217103530__alter_attendance_table.sql
Migration file for adding the localityCode and paymentStatus column in the attendance register table.

2025-01-13 09:23 UTC, Shashwat12-egov commented on backend/attendance/src/main/resources/db/migration/main/V20241226165900__alter_attendance_staff_table.sql
Migration file for adding the staffType column in the attendance staff table.

2025-01-20 09:40 UTC, yashita-egov commented
@coderabbitai review

2025-01-24 09:03 UTC, kavi-egov requested changes

2025-01-24 09:23 UTC, kavi-egov approved these changes

2025-01-24 09:23 UTC, merged