Attendance model changes for payments
egovernments/DIGIT-Works pull request #1857
Opened 2024-12-30 09:07 UTC by yashita-egov

2025-01-02 06:28 UTC, holashchand requested changes

2025-01-02 06:28 UTC, holashchand commented on libraries/works-services-common/src/main/java/org/egov/works/services/common/models/attendance/AttendanceRegister.java
> +    private WfStatus wfStatus = WfStatus.PENDINGFORAPPROVAL;
here it shouldn't be a short name, but a product related meaning full name. ie. approvalStatus or reviewStatus

2025-01-02 06:28 UTC, holashchand commented on libraries/works-services-common/src/main/java/org/egov/works/services/common/models/attendance/AttendanceRegister.java
> +    private WfStatus wfStatus = WfStatus.PENDINGFORAPPROVAL;
also don't hardcode it to be an enum, let it be any string here and it can have configurable validation while create or update. Also don't init the value here, you can add it while create. So that it can be reusable for others as well.

2025-01-05 06:29 UTC, yashita-egov commented on libraries/works-services-common/src/main/java/org/egov/works/services/common/models/attendance/AttendanceRegister.java
> +    private WfStatus wfStatus = WfStatus.PENDINGFORAPPROVAL;
changed it to reviewStatus

2025-01-20 10:17 UTC, holashchand commented
@coderabbitai review and update summary

2025-01-27 12:18 UTC, kavi-egov approved these changes

2025-01-27 12:20 UTC, kavi-egov approved these changes

2025-01-27 12:20 UTC, merged