New version of estimate API
egovernments/DIGIT-Works pull request #207
Opened 2022-12-22 08:52 UTC by subhashini-egov

Added a new version of the estimate API spec based on discussion with Ghanshyam. Checked into the estimate service as v2.0.0.

2022-12-22 09:42 UTC, rushang7-eGov requested changes

2022-12-22 09:42 UTC, rushang7-eGov commented on backend/estimate-service/Estimate-Service-2.0.0.yaml
> +servers:
Remove this section

2022-12-26 04:23 UTC, subhashini-egov reviewed
Removed the servers section at the bottom.

2022-12-26 04:25 UTC, rushang7-eGov approved these changes

2022-12-26 04:25 UTC, merged