Pfm 2155
egovernments/DIGIT-Works pull request #264
Opened 2023-01-11 14:30 UTC by vguptatw

Request you to please review it and take appropiate action. Changes related to : 
https://digit-discuss.atlassian.net/browse/PFM-2155

2023-01-18 08:53 UTC, subhashini-egov requested changes
I have just one comment about the roles constants. Can you please comment on that @vguptatw ?

2023-01-18 08:53 UTC, subhashini-egov commented on backend/attendance-service/src/main/java/org/egov/util/AttendanceServiceConstants.java
>      public static final String MASTER_TENANTS = "tenants";
@vguptatw - shouldn't we get roles from roles.json in MDMS? The risk here is that if the role codes change there, we will have to keep updating here.

2023-01-23 08:36 UTC, vguptatw commented
Hi @subhashini-egov , we have updated Register search API. Now it is configuration driven. If role is not superuser, then we restrict it to the tenant and registers this user is enrolled in. 

Request you to please review the changes.

2023-01-24 10:42 UTC, subhashini-egov approved these changes
Reviewed and approved.

2023-01-24 10:43 UTC, merged