Added Reject Modal and Remove unnecessary code
egovernments/DIGIT-Works pull request #43
Opened 2022-09-23 07:38 UTC by burhanj-eGov

2022-09-23 07:46 UTC, nipunarora-eGov approved these changes

2022-09-27 06:38 UTC, jagankumar-egov requested changes

2022-09-27 06:38 UTC, jagankumar-egov commented on frontend/micro-ui/web/micro-ui-internals/packages/modules/works/src/pages/employee/LOI/ViewLOI.js
> +        "pb",
Dont hardcode state tenant , there were many occurance for the same, @burhanj-eGov  can u check ?

2022-09-27 08:18 UTC, jagankumar-egov approved these changes

2022-09-27 08:18 UTC, merged